#Numpy Array Operations

In [ ]:
import numpy as np

## 1. Create a 1D NumPy Array

In [ ]:
temperatures_w1 = np.array ([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])

print("Week 1 Temperatures:",temperatures_w1)

Week 1 Temperatures: [22.5 25.3 20.8 23.4 26.1 24.8 21.9]


##2. Inspection and Properties

In [ ]:
print("Shape of the Array :",temperatures_w1.shape)
print("Data type of Array :",temperatures_w1.dtype)
print("Number of Elements :",temperatures_w1.size)

Shape of the Array : (7,)
Data type of Array : float64
Number of Elements : 7


##3. Array Operations


In [ ]:
temperatures_f = (temperatures_w1* 9/5) + 32

print("Temperatures in Fahrenheit :",temperatures_f)

Temperatures in Fahrenheit : [72.5  77.54 69.44 74.12 78.98 76.64 71.42]


In [ ]:
print("Maximum Temperature :",temperatures_w1.max())
print("Minimum Teprarature :",temperatures_w1.min())
print("Mean Teprarature :",temperatures_w1.mean())

Maximum Temperature : 26.1
Minimum Teprarature : 20.8
Mean Teprarature : 23.542857142857144


##4. Array Slicing and Indexing

In [ ]:
print("Temperatures for the 3 days :",temperatures_w1[:3])

print("Temperatures for the weekend :",temperatures_w1[-2:])

print("Temperatures for the middle 3 days :",temperatures_w1[2:5])

Temperatures for the 3 days : [22.5 25.3 20.8]
Temperatures for the weekend : [24.8 21.9]
Temperatures for the middle 3 days : [20.8 23.4 26.1]


## 5. Create a 2D Array

In [ ]:
temperatures = np.array([[22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],[19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1]])

print("2D Temperature Array :\n",temperatures)
print("\n","Dimension of the Array :",temperatures.ndim)

2D Temperature Array :
 [[22.5 25.3 20.8 23.4 26.1 24.8 21.9]
 [19.2 22.5 21.3 24.  23.5 22.8 20.1]]

 Dimension of the Array : 2


In [ ]:
print("Shape of the Array :",temperatures.shape)
print("Data type of Array :",temperatures.dtype)
print("Number of Elements :",temperatures.size)

Shape of the Array : (2, 7)
Data type of Array : float64
Number of Elements : 14


In [ ]:
print("Week 1 :",temperatures[0])
print("Week 2 :",temperatures[1])

print("\n","The temperatures for each week and the weekends :\n",temperatures[:,-2:])

Week 1 : [22.5 25.3 20.8 23.4 26.1 24.8 21.9]
Week 2 : [19.2 22.5 21.3 24.  23.5 22.8 20.1]

 The temperatures for each week and the weekends :
 [[24.8 21.9]
 [22.8 20.1]]


#Pandas Series

In [ ]:
import pandas as pd

##1. Creating Pandas Series

In [ ]:
marks = pd.Series([ 95, 92, 89, 85, 80],index = ['Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5'])
print(marks)

Rank1    95
Rank2    92
Rank3    89
Rank4    85
Rank5    80
dtype: int64


##2. Indexing and Slicing:

In [ ]:
print("1st rank student : ", marks.iloc[0])

1st rank student :  95


In [ ]:
print("Top 3 Rank \n")
print(marks.loc[["Rank1","Rank2","Rank3"]])

Top 3 Rank 

Rank1    95
Rank2    92
Rank3    89
dtype: int64


In [ ]:
print("3rd rank student mark : ", marks.iloc[2])

3rd rank student mark :  89


In [ ]:
print(marks[marks>90])

Rank1    95
Rank2    92
dtype: int64


##3. Manipulating Series

In [ ]:
marks["Rank1"]=100
print(marks)

Rank1    100
Rank2     92
Rank3     89
Rank4     85
Rank5     80
dtype: int64


In [ ]:
marks = marks.drop("Rank5")
print(marks)

Rank1    100
Rank2     92
Rank3     89
Rank4     85
dtype: int64


In [ ]:
cgpa = marks/10
print(cgpa)

Rank1    10.0
Rank2     9.2
Rank3     8.9
Rank4     8.5
dtype: float64


#Pandas DataFrame

##1. Creating Pandas DataFrame

In [ ]:
transactions = pd.DataFrame ({
    "TransactionID": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
     'ProductCategory': ['Electronics', 'Clothing', 'Electronics', 'Furniture',
'Clothing', 'Electronics', 'Furniture', 'Clothing', 'Furniture', 'Electronics'],
    'Region': ['North', 'South', 'North', 'East', 'West', 'North', 'East', 'West',
'South', 'North'],
    'Amount': [200, 150, 300, 450, 200, 250, 300, 180, 350, 400]
})

print(transactions)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400


##2. Data Exploration

In [ ]:
print("Head:\n",transactions.head())
print("Tail:\n",transactions.tail())
print('Shape:\n',transactions.shape)
print('Column names:\n',transactions.columns)
print('Data types:\n',transactions.dtypes)

Head:
    TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
Tail:
    TransactionID ProductCategory Region  Amount
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400
Shape:
 (10, 4)
Column names:
 Index(['TransactionID', 'ProductCategory', 'Region', 'Amount'], dtype='object')
Data types:
 TransactionID       int64
ProductCategory    object
Region             object
Amount              int64
dtype: object


In [ ]:
print(transactions[["ProductCategory","Amount"]])

  ProductCategory  Amount
0     Electronics     200
1        Clothing     150
2     Electronics     300
3       Furniture     450
4        Clothing     200
5     Electronics     250
6       Furniture     300
7        Clothing     180
8       Furniture     350
9     Electronics     400


In [ ]:
print(transactions.iloc[:,-3:])

  ProductCategory Region  Amount
0     Electronics  North     200
1        Clothing  South     150
2     Electronics  North     300
3       Furniture   East     450
4        Clothing   West     200
5     Electronics  North     250
6       Furniture   East     300
7        Clothing   West     180
8       Furniture  South     350
9     Electronics  North     400


In [ ]:
filter_data = transactions[(transactions['Region']=='North')&(transactions['Amount'] >200)]
print(filter_data)

   TransactionID ProductCategory Region  Amount
2            103     Electronics  North     300
5            106     Electronics  North     250
9            110     Electronics  North     400


In [ ]:
count = transactions["ProductCategory"].value_counts()
print(count)


ProductCategory
Electronics    4
Clothing       3
Furniture      3
Name: count, dtype: int64


In [ ]:
print(transactions["Region"].unique())

['North' 'South' 'East' 'West']


In [ ]:
mean_amount = transactions.groupby("Region")["Amount"].mean()
print(mean_amount)

Region
East     375.0
North    287.5
South    250.0
West     190.0
Name: Amount, dtype: float64


##3. Manipulating the DataFrame


In [ ]:
transactions.loc[transactions["TransactionID"] ==102,"Amount"] = 165
print(transactions)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400


In [ ]:
transactions["Discount"] = transactions["Amount"]/10

print(transactions)

   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
8            109       Furniture  South     350      35.0
9            110     Electronics  North     400      40.0


In [ ]:
transactions = transactions[transactions['TransactionID'] != 109]
print(transactions)


   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
9            110     Electronics  North     400      40.0


In [ ]:
transactions = transactions.drop(columns="Discount")

print(transactions)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
9            110     Electronics  North     400
